CONTRIBUTORS, playerctl/playerctl-cli.c, playerctl/playerctl-player.c, playerctl/playerctl-player.h
Hello again,
As promised in my previous PR, here are the changes I made to the CLI client. The intention is to fix some memory leaks, make it slightly more robust and improve its maintainability. By far the biggest change can be found in 7a98a0e9b42225107aebcdcde41cb0e39a894248, which greatly refactors the whole client. In a nutshell, I changed how the remaining command line arguments are handled:
I introduced a new struct, `PlayerCommand`, abstracting the player commands. Per command, there is an instance of this struct containing its name and a function pointer to a function that processes the command. As before, all leftover command line arguments are passed into a string array (`**command`), which is now scanned by `parse_player_command`. The first matching command is executed.
These …
=> Make the CLI client more robust

playerctl/playerctl-cli.c
Instead, multiply to count microseconds *then* truncate. This enables seeking fractional seconds.
=> Don't truncate offset to integer at parse-time

playerctl/playerctl-cli.c
Adds feature request #44.
Sends the command signal to all players if `--player=*` option is passed or to all players in a comma separated list `--player=cmus,spotify`.
=> CLI: send command to multiple players

README.md, playerctl/playerctl-cli.c
Fix for bug in https://github.com/acrisci/playerctl/pull/48#issuecomment-323161886. A misspelled player in a list of player names is now ignored.
I haven't yet thought about handling metadata or volume commands for multiple players as mentioned here https://github.com/acrisci/playerctl/issues/2#issuecomment-44230145.
=> Fix infinite loop on misspelling of player name

playerctl/playerctl-cli.c
Sorry for all the bugs. A segmentation fault occurs when playerctl is called without any music players specified with the --player option. This was due to strtok's first argument being NULL when called for the first time. I am unsure why I only get this on some machines and not others.
=> Fix segfault when strtok is called without a --player argument

doc/meson.build, doc/reference/meson.build, meson.build, meson_options.txt, playerctl/meson.build
This PR adds support for meson to playerctl. It works fine for everything but gtk-doc for me, still messing with that
=> add support for meson build system

playerctl/Makefile.am
Whilst packaging playerctl 0.5.0 for Debian [1] I refactored the introspection section of the Makefile to follow that of the many Gnome applications (e.g. Cheese) that provide GObject introspection.
I have build/user tested the refactored introspection configuration using the Python GIR bindings example, with no issues noted.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818044
=> Makefile.am: simplify introspection definitions

doc/meson.build, doc/reference/meson.build, meson.build, playerctl/meson.build
Hey there,
after porting a few more projects I've noticed a few things I didn't do quite right here. Changes include:
* Style fixes, the indention was really inconsistent.
* Removing unnecessary bits
* Use both_libraries instead of generating the shared and static library one at a time. This both looks nicer and is faster, since meson only compiles the required files once and links them differently instead of compiling everything twice. This however lifts the meson version requirement to 0.46, which has only been released a few days ago (however, I think most distros update meson regularly. Please tell me if that version requirement is okay, otherwise I'll revert this change)
* Set the correct version (please bump this the next time you do a new release :)
* Install manpages, no matter if …
=> Meson fixes

doc/playerctl.1
Bump version to 0.6.0 to match current release.
Perhaps updating the version in the manpage could be automated? It should be added to the pre-release checklist.
=> Bump playerctl version in manpage

CONTRIBUTORS, doc/meson.build, doc/playerctl.1.in
I guess this breaks the build for autotools, but I didn't bother messing with that since we'll drop that soon anyway.
=> Automatically set correct version of manpage

doc/meson.build, playerctl/meson.build
Doing it this way we have fancy error messages like:
```
playerctl/meson.build:71:6: ERROR:  Problem encountered: You need to have gobject-introspection installed to generate Gir data. Disable it with `-Dintrospection=false` if you don't want to build it
```
Which help inexperienced users to build playerctl, if they don't have gtk-doc or gobject-introspection installed.
=> Meson error reporting

playerctl/meson.build
=> meson: pass -DPLAYERCTL_COMPILATION to gir compiler

README.md
This pull request adds a link to a newly-published article on the Fedora Magazine about `playerctl`:
https://fedoramagazine.org/2-new-apps-for-music-tweakers-on-fedora-workstation/
=> README: Add link to Fedora Magazine article

README.md
This PR adds additional instructions for Fedora, Mageia, and openSUSE users to install a package instead of compiling `playerctl` from source.
=> README: Add package install instructions for Fedora, Mageia, openSUSE

doc/playerctl.1.in, meson.build
The manpage now uses [mdoc(7)](https://man.openbsd.org/mdoc.7), structuring info and making it easier to
write. Some other things:
- Expanded the section on format strings:
- List all variables that can be included.
- Add the `emoji()` function to the list.
- Split the example over two lines for brevity.
- Change the meson var `PLAYERCTL_RELEASE_MONTH` to
`PLAYERCTL_RELEASE_DATE`. The date is formatted as `Mon d, yyyy`, which
is required by mdoc.
=> Rewrite and expand manpage

playerctl/playerctl-formatter.c
This adds a formatter helper function, markup_escape(), to properly escape XML characters (e.g. <, >, &).
=> #133 Add markup_escape formatter helper function

playerctl/meson.build, playerctl/playerctl-cli.c, playerctl/playerctl-player.c
This addresses #113.
* Add a log domain in `meson.build`
* Add logging for the following:
* Playerctl version at startup
* Found players
* Command execution
* Warning for mpris;trackid not being a D-Bus object reference
* Player properties changed events
* Warning when playback status is not set on track change
* Capitalize warning for unknown playback state
* Player seeked event
* Warning for Spotify not using the D-Bus property cache
* Warning for D-Bus socket address when attempting to list player names on a bus
* Getting bus names for player names, and which method is being used
* Warning for bus address being set incorrectly in player init
* Initializing cache for player
=> Add debug logging

README.md
Hi @acrisci!
I [recently contributed](http://git.savannah.gnu.org/cgit/guix.git/commit/gnu/packages/music.scm?id=1c463524c8325c434a437f358e71cd7191dce267) a package definition for playerctl into the [Guix](https://guix.gnu.org) package repository.  This is useful not only for those who have the Guix System distribution installed, but also for anyone who might install the standalone Guix package manager on their existing Linux distribution.
This PR adds some basic instructions on how one can install playerctl using the `guix` command.  If you think it isn't notable enough for inclusion as README section, I will understand; please feel free to close the PR in that case.
By the way, thanks for making playerctl!
=> Add Guix installation instructions for playerctl

examples/notify.py
I think this is a short and interesting use of playerctl.
Based on the player manager example.
Feel free to close if it is beyond the scope of an example.
=> Add examples/notify.py: Notify of playing title

playerctl/playerctl-daemon.c, test/test_daemon.py
This implements the feature suggested in #170
The daemon exposes a dbus method called ```Shift```, that the user can interact with to request a shift. At the moment that dbus method needs to be interacted with manually using a tool like dbus-send.
The following command requests a shift:
> dbus-send --type=method_call --dest=org.mpris.MediaPlayer2.playerctld /org/mpris/MediaPlayer2 com.github.altdesktop.playerctld.Shift
This dbus command can be incorporated in playerctl, so that the user can do something like ```playerctl shift``` which will execute the above dbus method call. I tried my best to implement the dbus method, but I could not figure out how to send a proper response, so I have to use ```type=method_call``` instead of ```--print-reply```.
Additionally, I have added some logic to …
=> implement a shift feature for playerctld

playerctl/playerctl-daemon.c, test/test_daemon.py
Added a new `unshift` option to `playerctld`. Calling `playerctld unshift` will rotate the player queue in reverse, which is useful when more then two mpris dbus processes are active.
=> added unshift option to playerctld for moving queue in reverse

playerctl/playerctl-cli.c
There is a small typo in playerctl/playerctl-cli.c.
Should read `property` rather than `propery`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, propery -> property

README.md, doc/playerctl.1.in, playerctl/playerctl-formatter.c, test/test_format.py
hello, this adds a `trunc()` helper function to truncate long text
eg. on my statusbar where there is limited space I could shorted long track names
eg
```shell
$ playerctl metadata -f '{{lc(status)}} "{{title}}"'
playing "Doctor Blowfin's Water Cruiser"
$ playerctl metadata -f '{{lc(status)}} "{{trunc(title, 25)}}"'
playing "Doctor Blowfin's Water Cr…"
```
if you'll accept this PR I can update it for docs/readme/etc
thanks!
=> Add `trunc` helper function

data/playerctl.zsh
Hi there! Thanks for all the work that you do on playerctl. I just saw a little typo while using it in the zsh completions so I fixed that up and here it is! That's all, a pretty simple contribution. It's not much, but it's honest work :)
=> Fix typo in zsh completions (palyer -> player)
